name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-staging
jobs:
  deploy:
    uses: eco/workflows/.github/workflows/deploy-to-eks.yml@v20231102
    with:
      appname: solver
      assumed-role: arn:aws:iam::027715947294:role/solver-eks-actions-beam-staging
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: staging
      ghsha: fd85f9aa938ce9e6638676d1501e21eb6b9ca12a 
      targetenv: staging
