name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-staging
jobs:
  deploy:
    uses: eco/workflows/.github/workflows/deploy-to-eks.yml@v20231102
    with:
      appname: solver
      assumed-role: arn:aws:iam::027715947294:role/solver-eks-actions-beam-staging
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: staging
      ghsha: fd7a77f4ca940466d4231d899f898412d9ba37c8 
      targetenv: staging
