name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-staging

permissions:
  contents: read  # Allow access to repository content
  actions: read
jobs:
  deploy:
    uses: ./.github/workflows/deploy-to-eks.yml
    with:
      appname: solver
      assumed-role: arn:aws:iam::027715947294:role/solver-eks-actions-beam-staging
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: staging
      ghsha: e4c823a00ef065ea635afc31e274fd2ffb08692e
      targetenv: staging
