name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-staging
jobs:
  deploy:
    uses: eco/workflows/.github/workflows/deploy-to-eks.yml@v20231102
    with:
      appname: solver
      assumed-role: arn:aws:iam::165381489880:role/solver-eks-actions-beam-production
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: staging
      ghsha: 3c27c06feec4c236a5efede2c4aded1a246f5700
      targetenv: staging
