name: Build Push to Amazon ECR

on:
  push:
    branches:
      - release-preproduction
jobs:
  deploy:
    uses: eco/workflows/.github/workflows/deploy-to-eks.yml@v20231102
    with:
      appname: solver-preproduction
      assumed-role: arn:aws:iam::165381489880:role/solver-eks-actions-beam-production
      aws-region: us-east-2
      ecr-repository: eco-solver
      ghenv: production
      ghsha: fd85f9aa938ce9e6638676d1501e21eb6b9ca12a
      targetenv: preproduction
